---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [master, main, production]
    #branches-ignore: [master, main, production]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main, production]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          # list of file types to validate (everything else ignored)
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSX: true
          VALIDATE_CSS: true
          VALIDATE_TSX: true
          VALIDATE_TYPESCRIPT_ES: true
          # path to lint config files
          LINTER_RULES_PATH: /
          # eslint config file location
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          # use prettier JS style
          JAVASCRIPT_DEFAULT_STYLE: standard/prettier
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.js
          # lint only src folder
          FILTER_REGEX_INCLUDE: .*src/.*
          # only lint new or modified files
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
